import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { enqueueSnackbar } from "notistack";
import {
  FaUsers,
  FaClipboardList,
  FaMoneyBillWave,
  FaCalendarDay,
  FaPlus,
  FaUserShield,
} from "react-icons/fa";

import { getStaffReports, addStaff, updateStaff, deleteStaff } from "../../https";
import FullScreenLoader from "../../components/shared/FullScreenLoader";
import ConfirmDialog from "../../components/shared/ConfirmDialog";
import Modal from "../../components/shared/Modal";
import StaffTable from "../../components/management/StaffTable";
import StaffFormModal from "../../components/management/StaffFormModal";
import Register from "../../components/auth/Register";

const currency = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0,
});

const StaffManagement = () => {
  useEffect(() => {
    document.title = "Satya POS | Staff";
  }, []);

  const queryClient = useQueryClient();
  const userData = useSelector((state) => state.user);
  const isAdmin = userData?.role === "Admin";

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingStaff, setEditingStaff] = useState(null);
  const [deletingStaff, setDeletingStaff] = useState(null);
  const [isCreateAccountOpen, setIsCreateAccountOpen] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["staff-reports"],
    queryFn: async () => {
      const response = await getStaffReports();
      return response.data;
    },
    refetchInterval: 30000,
  });

  const invalidate = () =>
    queryClient.invalidateQueries({ queryKey: ["staff-reports"] });

  const createMutation = useMutation({
    mutationFn: addStaff,
    onSuccess: () => {
      enqueueSnackbar("Staff added successfully!", { variant: "success" });
      setIsFormOpen(false);
      invalidate();
    },
    onError: (error) => {
      enqueueSnackbar(error?.response?.data?.message || "Failed to add staff", {
        variant: "error",
      });
    },
  });

  const updateMutation = useMutation({
    mutationFn: updateStaff,
    onSuccess: () => {
      enqueueSnackbar("Staff updated successfully!", { variant: "success" });
      setIsFormOpen(false);
      setEditingStaff(null);
      invalidate();
    },
    onError: (error) => {
      enqueueSnackbar(
        error?.response?.data?.message || "Failed to update staff",
        { variant: "error" }
      );
    },
  });

  const deleteMutation = useMutation({
    mutationFn: deleteStaff,
    onSuccess: () => {
      enqueueSnackbar("Staff removed successfully!", { variant: "success" });
      setDeletingStaff(null);
      invalidate();
    },
    onError: (error) => {
      enqueueSnackbar(
        error?.response?.data?.message || "Failed to remove staff",
        { variant: "error" }
      );
      setDeletingStaff(null);
    },
  });

  if (isLoading) return <FullScreenLoader />;

  const staff = data?.data || [];

  const totals = staff.reduce(
    (sum, member) => ({
      totalOrders: sum.totalOrders + (member.totalOrders || 0),
      totalRevenue: sum.totalRevenue + (member.totalRevenue || 0),
      weeklyRevenue: sum.weeklyRevenue + (member.weeklyRevenue || 0),
      monthlyRevenue: sum.monthlyRevenue + (member.monthlyRevenue || 0),
      todayRevenue: sum.todayRevenue + (member.todayRevenue || 0),
    }),
    {
      totalOrders: 0,
      totalRevenue: 0,
      weeklyRevenue: 0,
      monthlyRevenue: 0,
      todayRevenue: 0,
    }
  );

  const cards = [
    { title: "Total Staff", value: staff.length, icon: <FaUsers /> },
    {
      title: "Total Orders Taken",
      value: totals.totalOrders,
      icon: <FaClipboardList />,
    },
    {
      title: "Total Revenue",
      value: currency.format(totals.totalRevenue),
      icon: <FaMoneyBillWave />,
    },
    {
      title: "This Week",
      value: currency.format(totals.weeklyRevenue),
      icon: <FaMoneyBillWave />,
    },
    {
      title: "This Month",
      value: currency.format(totals.monthlyRevenue),
      icon: <FaMoneyBillWave />,
    },
    {
      title: "Today's Revenue",
      value: currency.format(totals.todayRevenue),
      icon: <FaCalendarDay />,
    },
  ];

  const handleSubmit = (formData) => {
    if (editingStaff) {
      updateMutation.mutate({ id: editingStaff._id, ...formData });
    } else {
      createMutation.mutate(formData);
    }
  };

  return (
    <div className="min-h-screen bg-[#1f1f1f] px-6 py-8">
      <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">Staff Reports</h1>
          <p className="text-gray-400 mt-2">
            Manage staff and track orders taken & revenue generated by each.
          </p>
        </div>

        {isAdmin && (
          <div className="flex gap-3">
            <button
              onClick={() => setIsCreateAccountOpen(true)}
              className="bg-[#333] text-white px-5 py-3 rounded-xl font-semibold flex items-center gap-2"
            >
              <FaUserShield />
              Create Login Account
            </button>

            <button
              onClick={() => {
                setEditingStaff(null);
                setIsFormOpen(true);
              }}
              className="bg-yellow-400 text-black px-5 py-3 rounded-xl font-semibold flex items-center gap-2"
            >
              <FaPlus />
              Add Staff
            </button>
          </div>
        )}
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-5 mt-8">
        {cards.map((card) => (
          <div key={card.title} className="bg-[#262626] rounded-2xl p-5">
            <div className="flex justify-between items-center">
              <p className="text-gray-400 text-sm">{card.title}</p>
              <div className="text-yellow-400 text-xl">{card.icon}</div>
            </div>
            <h2 className="text-white text-xl font-bold mt-2">{card.value}</h2>
          </div>
        ))}
      </div>

      <StaffTable
        staff={staff}
        onEdit={
          isAdmin
            ? (member) => {
                setEditingStaff(member);
                setIsFormOpen(true);
              }
            : undefined
        }
        onDelete={isAdmin ? (member) => setDeletingStaff(member) : undefined}
      />

      {isAdmin && (
        <>
          <StaffFormModal
            isOpen={isFormOpen}
            onClose={() => {
              setIsFormOpen(false);
              setEditingStaff(null);
            }}
            onSubmit={handleSubmit}
            initialData={editingStaff}
            isSubmitting={createMutation.isPending || updateMutation.isPending}
          />

          <ConfirmDialog
            isOpen={!!deletingStaff}
            title="Remove staff member?"
            message={
              deletingStaff
                ? `This will permanently remove ${deletingStaff.name} from staff.`
                : ""
            }
            confirmText="Remove"
            cancelText="Cancel"
            onConfirm={() => deleteMutation.mutate(deletingStaff._id)}
            onCancel={() => setDeletingStaff(null)}
          />

          <Modal
            isOpen={isCreateAccountOpen}
            onClose={() => setIsCreateAccountOpen(false)}
            title="Create Employee Login Account"
          >
            <Register setIsRegister={() => setIsCreateAccountOpen(false)} />
          </Modal>
        </>
      )}
    </div>
  );
};

export default StaffManagement;