import React, { useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  FaUsers,
  FaClipboardList,
  FaMoneyBillWave,
  FaCalendarDay,
} from "react-icons/fa";

import { getStaffReports } from "../../https";
import FullScreenLoader from "../../components/shared/FullScreenLoader";

const currency = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0,
});

const StaffManagement = () => {
  useEffect(() => {
    document.title = "Satya POS | Staff";
  }, []);

  const { data, isLoading } = useQuery({
    queryKey: ["staff-reports"],
    queryFn: async () => {
      const response = await getStaffReports();
      return response.data;
    },
    refetchInterval: 30000,
  });

  if (isLoading) return <FullScreenLoader />;

  const staff = data?.data || [];

  const totals = staff.reduce(
    (sum, member) => ({
      totalOrders: sum.totalOrders + (member.totalOrders || 0),
      revenue: sum.revenue + (member.revenue || 0),
      todayRevenue: sum.todayRevenue + (member.todayRevenue || 0),
    }),
    { totalOrders: 0, revenue: 0, todayRevenue: 0 }
  );

  const cards = [
    {
      title: "Total Staff",
      value: staff.length,
      icon: <FaUsers />,
    },
    {
      title: "Total Orders Taken",
      value: totals.totalOrders,
      icon: <FaClipboardList />,
    },
    {
      title: "Total Revenue",
      value: currency.format(totals.revenue),
      icon: <FaMoneyBillWave />,
    },
    {
      title: "Today's Revenue",
      value: currency.format(totals.todayRevenue),
      icon: <FaCalendarDay />,
    },
  ];

  return (
    <div className="min-h-screen bg-[#1f1f1f] px-6 py-8">
      <h1 className="text-3xl font-bold text-white">Staff Reports</h1>
      <p className="text-gray-400 mt-2">
        Orders taken and revenue generated by each staff member.
      </p>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mt-8">
        {cards.map((card) => (
          <div key={card.title} className="bg-[#262626] rounded-2xl p-5">
            <div className="flex justify-between items-center">
              <p className="text-gray-400">{card.title}</p>
              <div className="text-yellow-400 text-2xl">{card.icon}</div>
            </div>
            <h2 className="text-white text-2xl font-bold mt-2">
              {card.value}
            </h2>
          </div>
        ))}
      </div>

      <div className="bg-[#262626] rounded-2xl border border-gray-700 mt-8 overflow-x-auto">
        <table className="w-full">
          <thead className="border-b border-gray-700 text-gray-400">
            <tr>
              <th className="text-left p-4">Staff</th>
              <th className="text-left">Role</th>
              <th className="text-left">Status</th>
              <th className="text-left">Total Orders</th>
              <th className="text-left">Revenue</th>
              <th className="text-left">Today's Revenue</th>
            </tr>
          </thead>

          <tbody>
            {staff.length ? (
              staff.map((member) => (
                <tr key={member._id} className="border-b border-gray-800">
                  <td className="p-4 text-white font-semibold">
                    {member.name}
                  </td>
                  <td className="text-gray-300">{member.role || "-"}</td>
                  <td>
                    <span
                      className={`px-3 py-1 rounded-full text-sm ${
                        member.status === "Inactive"
                          ? "bg-gray-600 text-white"
                          : "bg-green-600 text-white"
                      }`}
                    >
                      {member.status || "Active"}
                    </span>
                  </td>
                  <td className="text-white">{member.totalOrders}</td>
                  <td className="text-white">
                    {currency.format(member.revenue || 0)}
                  </td>
                  <td className="text-[#f6b100] font-semibold">
                    {currency.format(member.todayRevenue || 0)}
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={6} className="text-center text-gray-500 p-6">
                  No staff added yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default StaffManagement;
